### ISSUE TITLE
Public Release Roadmap

### ISSUE THREAD

**Issue by alexban01** [royrovp/ArmA-3-Guides#35]
This issue shall not be closed until all points have been addressed.

This page is meant as a collection of all features we want to have in the wiki before releasing this to the rest of the unit. 
Feel free to add / remove anything you like.

- Medical:
  - [ ] Infantry Ace Medical #25
  - [ ] Medics Ace Medical #33
- Trainings:
  - [ ] Basic Combat Training #34
  - [ ] TFAR Beginners guide #27
